platform: linux

image_resource:
  type: docker-image
  source:
    repository: gradle
    tag: alpine

inputs:
- name: example-api

outputs:
- name: build

run:
  user: root
  path: gradle
  args:
    - -b example-api/build.gradle
    - buildInParent

