platform: linux

image_resource:
  type: docker-image
  source:
    repository: gradle
    tag: alpine

inputs:
- name: source

outputs:
- name: build

run:
  user: root
  path: gradle
  args:
    - -PbuildDir=../build
    - --build-file
    - source/build.gradle
    - build

