resource_types:

# maven resource to allow us to write to maven repo such as sonatype/nexus
- name: maven-resource
  type: docker-image
  source:
    repository: pivotalpa/maven-resource
    tag: v1.3.3

resources:

  - name: version
    type: semver
    source:
      driver: git
      uri: git@github.com:duncanatkinson/example-api.git
      branch: version
      file: version
      private_key: {{github-private-key}}

  - name: example-api
    type: git
    source:
      uri: git@github.com:duncanatkinson/example-api.git
      branch: master
      private_key: {{github-private-key}}

  - name: maven-release
    type: maven-resource
    source:
      url: https://10.34.64.218/repository/releases
      snapshot_url: https://10.34.64.218:8081/repository/snapshots
      artifact: example.nationaltrust:example-webapp:jar
      username: admin
      password: admin123
      disable_redeploy: true

jobs:
  - name: build-example-api
    plan:
      - put: version
        params: {bump: patch}
      - get: example-api
        trigger: true
      - task: unit
        file: example-api/ci/concorse-unit-task.yml
      - put: maven-release
        params:
          file: example-api/build/lib/*.jar
          pom_file: example-api/pom.xml
          version_file: version/version