resource_types:

# maven resource to allow us to write to maven repo such as sonatype/nexus
- name: maven-resource
  type: docker-image
  source:
    repository: pivotalpa/maven-resource
    tag: 1.3.2

resources:

  - name: version
    type: semver
    source:
      driver: git
      uri: git@github.com:duncanatkinson/example-api.git
      branch: version
      file: version
      private_key: {{github-private-key}}

  - name: source
    type: git
    source:
      uri: git@github.com:duncanatkinson/example-api.git
      branch: master
      private_key: {{github-private-key}}

  - name: release
    type: maven-resource
    source:
      url: http://nexus.nt.ad.local:8081/nexus/content/repositories/releases
      artifact: example.nationaltrust:example-api:jar
      username: deployment
      password: {{nexus-deployment-password}}
      disable_redeploy: true

jobs:
  - name: build-example-api
    plan:
      - get: version
        params:
          pre: rc
          file: version
      - get: source
        trigger: true
      - task: build & unit test
        file: source/ci/build.yml
      - put: release
        params:
          file: build/libs/example-api.jar
          version_file: version/version