resource_types:

# maven resource to allow us to write to maven repo such as sonatype/nexus
- name: maven-resource
  type: docker-image
  source:
    repository: pivotalpa/maven-resource
    tag: v1.3.3

resources:

  - name: version
    type: semver
    source:
      driver: git
      uri: git@github.com:duncanatkinson/example-api.git
      branch: version
      file: version
      private_key: {{github-private-key}}

  - name: example-api
    type: git
    source:
      uri: git@github.com:duncanatkinson/example-api.git
      branch: master
      private_key: {{github-private-key}}

  - name: example-api-release
    type: maven-resource
    source:
      url: http://10.34.64.218/nexus/content/repositories/releases
      artifact: example.nationaltrust:example-api:jar
      username: admin
      password: admin123
      disable_redeploy: true

jobs:
  - name: build-example-api
    plan:
      - get: version
        params: {bump: patch}
      - get: example-api
        trigger: true
      - task: build & unit test
        file: example-api/ci/concorse-test.yml
      - put: example-api-release
        params:
          file: example-api/build/libs/example-api.jar
          version_file: version/version
      - put: version